"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# import sys
# sys.path.insert(0, "/Users/Richard/Projects/Star Centre/Crayfish/crayfish")
# sys.path.insert(0, "/Users/Richard/Projects/Star Centre/Crayfish/crayfish/pypix")

from setuptools import setup

APP = ['Crayfish.py']
DATA_FILES = []


setup(
    app=APP,
    data_files=DATA_FILES,
    options=dict(py2app=dict(
        argv_emulation= True,
        site_packages= True,
        matplotlib_backends="wxagg",
        packages="crayfish"
    )),
    setup_requires=['py2app'],
)


